import { Movie } from "@/lib/types";

// Poster art is sourced from Wikipedia's public REST API (theatrical
// release posters used editorially on each film's article) and mirrored
// locally under /public/movies so the app never depends on a live
// third-party image host. Palette values are sampled from the poster
// art itself (top/bottom region average, boosted for glow use).
//
// backdropUrl points at a pre-blurred rendition of the same poster
// (generated once via sharp, see git history) rather than blurring the
// poster at runtime with a CSS filter — the source posters are small
// (~250x370, capped by Wikipedia's fair-use policy for non-free media),
// so a runtime `filter: blur()` on a 6x-upscaled image compositing under
// semi-transparent overlays triggers a Chromium rendering bug that
// paints the scrim as fully opaque. Pre-blurring the asset sidesteps it
// entirely and looks better besides.
const rawMovies: Omit<Movie, "backdropUrl">[] = [
  {
    id: "the-intern",
    title: "The Intern",
    year: 2015,
    genres: ["comedy", "drama"],
    levelFit: ["intermediate"],
    dialogueComplexity: 3,
    pace: 2,
    posterUrl: "/movies/the-intern.jpg",
    palette: ["#b28087", "#bd9c9e"],
    logline: "A retired widower becomes a senior intern at a fashion startup.",
    runtime: 121,
  },
  {
    id: "paddington-2",
    title: "Paddington 2",
    year: 2017,
    genres: ["comedy", "animation"],
    levelFit: ["beginner", "intermediate"],
    dialogueComplexity: 1,
    pace: 3,
    posterUrl: "/movies/paddington-2.jpg",
    palette: ["#2676c0", "#7a80ab"],
    logline: "A polite bear tries to buy the perfect gift and lands in trouble.",
    runtime: 103,
  },
  {
    id: "arrival",
    title: "Arrival",
    year: 2016,
    genres: ["scifi", "drama", "mystery"],
    levelFit: ["advanced"],
    dialogueComplexity: 5,
    pace: 2,
    posterUrl: "/movies/arrival.jpg",
    palette: ["#a38962", "#8b7c4b"],
    logline: "A linguist races to decode an alien language before it's too late.",
    runtime: 116,
  },
  {
    id: "la-la-land",
    title: "La La Land",
    year: 2016,
    genres: ["romance", "drama"],
    levelFit: ["intermediate", "advanced"],
    dialogueComplexity: 3,
    pace: 3,
    posterUrl: "/movies/la-la-land.png",
    palette: ["#000dd6", "#2019bd"],
    logline: "A pianist and an actress chase their dreams — and each other — in LA.",
    runtime: 128,
  },
  {
    id: "knives-out",
    title: "Knives Out",
    year: 2019,
    genres: ["mystery", "thriller", "comedy"],
    levelFit: ["advanced"],
    dialogueComplexity: 4,
    pace: 4,
    posterUrl: "/movies/knives-out.jpeg",
    palette: ["#d69800", "#c62411"],
    logline: "A detective unravels a web of lies after a family patriarch's death.",
    runtime: 130,
  },
  {
    id: "up",
    title: "Up",
    year: 2009,
    genres: ["animation", "drama", "comedy"],
    levelFit: ["beginner"],
    dialogueComplexity: 1,
    pace: 2,
    posterUrl: "/movies/up.jpg",
    palette: ["#5c9beb", "#9fa1bb"],
    logline: "An old man ties balloons to his house to chase a lifelong dream.",
    runtime: 96,
  },
  {
    id: "mad-max-fury-road",
    title: "Mad Max: Fury Road",
    year: 2015,
    genres: ["action", "scifi"],
    levelFit: ["intermediate"],
    dialogueComplexity: 2,
    pace: 5,
    posterUrl: "/movies/mad-max-fury-road.jpg",
    palette: ["#7ba432", "#f1a42b"],
    logline: "A high-octane chase across a scorched wasteland toward freedom.",
    runtime: 120,
  },
  {
    id: "the-devil-wears-prada",
    title: "The Devil Wears Prada",
    year: 2006,
    genres: ["comedy", "drama"],
    levelFit: ["intermediate"],
    dialogueComplexity: 3,
    pace: 3,
    posterUrl: "/movies/the-devil-wears-prada.jpg",
    palette: ["#d78983", "#d19689"],
    logline: "A new assistant survives the demands of a ruthless fashion editor.",
    runtime: 109,
  },
  {
    id: "coco",
    title: "Coco",
    year: 2017,
    genres: ["animation", "drama"],
    levelFit: ["beginner"],
    dialogueComplexity: 1,
    pace: 3,
    posterUrl: "/movies/coco.jpg",
    palette: ["#bb6ab4", "#bf3030"],
    logline: "A boy crosses into the Land of the Dead to prove his family's legacy.",
    runtime: 105,
  },
  {
    id: "gone-girl",
    title: "Gone Girl",
    year: 2014,
    genres: ["thriller", "mystery"],
    levelFit: ["advanced"],
    dialogueComplexity: 5,
    pace: 3,
    posterUrl: "/movies/gone-girl.jpg",
    palette: ["#436e93", "#a1b8a8"],
    logline: "A husband becomes the prime suspect when his wife disappears.",
    runtime: 149,
  },
  {
    id: "zootopia",
    title: "Zootopia",
    year: 2016,
    genres: ["animation", "comedy", "mystery"],
    levelFit: ["beginner", "intermediate"],
    dialogueComplexity: 2,
    pace: 3,
    posterUrl: "/movies/zootopia.jpg",
    palette: ["#c2ac99", "#7e5874"],
    logline: "A rookie rabbit cop teams up with a con-artist fox to crack a case.",
    runtime: 108,
  },
  {
    id: "inception",
    title: "Inception",
    year: 2010,
    genres: ["scifi", "thriller", "action"],
    levelFit: ["advanced"],
    dialogueComplexity: 5,
    pace: 4,
    posterUrl: "/movies/inception.jpg",
    palette: ["#1f83b7", "#1871bf"],
    logline: "A thief who steals secrets from dreams is offered one last job.",
    runtime: 148,
  },
  {
    id: "crazy-rich-asians",
    title: "Crazy Rich Asians",
    year: 2018,
    genres: ["romance", "comedy", "drama"],
    levelFit: ["intermediate"],
    dialogueComplexity: 3,
    pace: 3,
    posterUrl: "/movies/crazy-rich-asians.png",
    palette: ["#8f684c", "#30a681"],
    logline: "A trip to meet the family reveals just how rich her boyfriend is.",
    runtime: 120,
  },
  {
    id: "spider-verse",
    title: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    genres: ["animation", "action", "scifi"],
    levelFit: ["beginner", "intermediate"],
    dialogueComplexity: 2,
    pace: 5,
    posterUrl: "/movies/spider-verse.png",
    palette: ["#c79961", "#c34f13"],
    logline: "A teenager discovers he's one of many Spider-People across universes.",
    runtime: 117,
  },
];

export const movies: Movie[] = rawMovies.map((m) => ({
  ...m,
  backdropUrl: `/movies/backdrops/${m.id}.jpg`,
}));

export function getMovieById(id: string): Movie | undefined {
  return movies.find((m) => m.id === id);
}
